// Backgrounds
IMAGE bg_title "gfx/bg_title.png" BEST
IMAGE bg_gameplay_easy "gfx/bg_gameplay_easy.png" BEST
IMAGE bg_gameplay_normal "gfx/bg_gameplay_normal.png" BEST
IMAGE bg_gameplay_hard "gfx/bg_gameplay_hard.png" BEST
// Sprites (32x32px = 4x4 tiles)
SPRITE spr_note "gfx/spr_notes.png" 4 4 BEST 0
SPRITE spr_hitzone "gfx/spr_hitzone.png" 4 4 BEST 0
SPRITE spr_explosion "gfx/spr_explosion.png" 4 4 BEST 0
SPRITE spr_countdown "gfx/spr_countdown.png" 8 8 BEST 0
// Sound Effects
WAV sfx_1 "snd/1.wav" XGM
WAV sfx_2 "snd/2.wav" XGM
WAV sfx_3 "snd/3.wav" XGM
WAV sfx_intro "snd/intro.wav" XGM
WAV sfx_score_0 "snd/score_0.wav" XGM
WAV sfx_score_1000 "snd/score_1000.wav" XGM
WAV sfx_score_200k "snd/score_200k.wav" XGM
WAV sfx_score_600k "snd/score_600k.wav" XGM
WAV sfx_score_900k "snd/score_900k.wav" XGM
// Music (auto-generated by build_pipeline.py)
// Music (auto-generated by build_pipeline.py)
// Music (auto-generated by build_pipeline.py)
// Music (auto-generated by build_pipeline.py)
// Music (auto-generated by build_pipeline.py)
// Music (auto-generated by build_pipeline.py)

// Music (auto-generated by build_pipeline.py)
XGM song_0 "music/song_0.vgm"
